### ISSUE TITLE
v 1.1.1 and v 1.0.1difference

### ISSUE THREAD

**Issue by lion-no-back** [vyleung/logseq-helium-plugin#3]
Hello, the effect of the plugin is very nice, but there is a small problem. In the latest version of v.1.1.1, the video on my side can't be floated. I can use v1.0.1.Besides,my computer is win11. I really like this one you developed. plugin

**Comment by vyleung** [comment]
hi! is the video you're floating a youtube video or another type of video? also, is the balloon icon being shown when you attempt to float the video?

**Comment by lion-no-back** [comment]
Other types of videos，then show the balloon icon but it doesn't work

**Comment by vyleung** [comment]
gotcha - would you mind sending me a link to a video that isn't able to be floated?

**Comment by lion-no-back** [comment]
The videos I downloaded from Bilibili are offline what else can I offer

**Comment by lion-no-back** [comment]
https://user-images.githubusercontent.com/100990301/167238811-becf0e24-dae9-44cb-8885-f198e2c8b207.mp4

**Comment by vyleung** [comment]
the video was super helpful - thanks! this issue should hopefully be fixed in [v.1.1.2](https://github.com/vyleung/logseq-helium-plugin/releases/tag/v.1.1.2)

**Comment by lion-no-back** [comment]
Hmm, looking forward to it

**Comment by vyleung** [comment]
the marketplace should now have v.1.1.2 - please update the plugin and let me know if the issue is fixed

**Comment by lion-no-back** [comment]
You are very efficient. I just tried it, but it still doesn't work.

**Comment by lion-no-back** [comment]
I'm sorry, there was a problem with the test, it's ok, it's great

**Comment by lion-no-back** [comment]
Sorry, there was a problem with the test, and now it can be used normally.

**Comment by lion-no-back** [comment]
great！！！

**Comment by lion-no-back** [comment]
awesome

**Comment by vyleung** [comment]
happy to hear that it's been fixed 🙂
